apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{  .Release.Name  }}-postgres-pv"
spec:
  capacity:
    storage: {{  .Values.database.storage  }}
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  claimRef:
    name: "{{ .Release.Name }}-postgres-pvc"
    namespace: {{ .Values.database.namespace | default "database" }}
  hostPath:
    path: {{  index .Values.database "pv-path" | quote  }}