apiVersion: v1
kind: ConfigMap
metadata:
  name: db-sql-scripts
  namespace: database
data:
  schema.sql: |
{{ .Files.Get "sqlfiles/schema.sql" | indent 4 }}
  seed.sql: |
{{ .Files.Get "sqlfiles/seed.sql" | indent 4 }}