apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-postgres-pvc"
  namespace: {{ .Values.database.namespace | default "database" }}
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{  .Values.database.storage  }}
  storageClassName: manual
  volumeName: "{{ .Release.Name }}-postgres-pv"