apiVersion: v1
kind: Service
metadata:
  name: {{  .Release.Name  }}-postgres-service
  namespace: {{  .Values.database.namespace  }}
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{  .Values.database.service.type | default "ClusterIP"  }}      
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{  .Values.database.port  }}
      targetPort: {{  .Values.database.port  }}