apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: database
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.DB_NAME | quote }}
  POSTGRES_USER: {{ .Values.postgres.DB_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.DB_PASSWORD | quote }}