apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
    Namespace: database
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  persistentVolumeReclaimPolicy: Retain