apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
  namespace: database
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secrets
      containers:
        - name: db-init
          image: ghcr.io/n-h-a-m/devops/backend:latest
          command: ["python", "seed.py"] # Replace with your actual seed command or "alembic", "upgrade", "head"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-db-secret
                  key: DATABASE_URL
      restartPolicy: OnFailure