backend:
    databaseUrl: ENC[AES256_GCM,data:pf9++LQ7qOaCNioxi+Um77tYpR/3IjIx4O/6VzmeDeKT1XA1xU/NrQIbjyB1FMxfr7w8eKmMiEJeBYu0GFzVscl7zUBJXu9PKCyug9XRk5bD,iv:Ut+mNGex2jh5FTEg8ou8IiA/wV2nRHyzf9TZCaemfG0=,tag:VDHB/igsBvuTtYhe1F5zvA==,type:str]
imagePullSecret:
    username: ENC[AES256_GCM,data:cRVAHhrmqw==,iv:fiVEcbjV4cs7Rml2DgVtkgwNOX3G61SwU9v/wi/Wfic=,tag:Cdo2fS+BCcth3D960Wk3CA==,type:str]
    password: ENC[AES256_GCM,data:y2/jmY4cfEicmc6AIFz444i6Pr+9HU48dXNQ2dUyHBQS4NKzBMBICQ==,iv:2FgrXkFyMvrooz1WAD1smxJ9qGShO6n5ER70iicCPOU=,tag:64pdiEnnxLzcbbiA7tye2Q==,type:str]
postgres:
    DB_USER: ENC[AES256_GCM,data:ceIh,iv:s7pw0/EfrebIzQ1cLZIr8dM57bDueezB/woIIz32ZUk=,tag:u54iC3ndGNJ+DttSOyksPA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:sDLMXLj9,iv:qEi60M4+2nQYg9wB352cdxA0uDPb5mzpekcMtCKHfQc=,tag:iuOuOGoPeTJxF8K7CJ5xMA==,type:str]
    DB_NAME: ENC[AES256_GCM,data:E1zIen/3MyA=,iv:5EF2gvtOmY5EZ16PtAmCQCKJUQHho/I2ct36Kp3wGdw=,tag:hZbPNKumj7IgqwpdWiBreg==,type:str]
    PROJECT_ROOT: ENC[AES256_GCM,data:Qw==,iv:40L+R0V30Pk5D+hTRrbGJX5L5IGp/k+6YksABVtZM7A=,tag:z11Wl+fQNL7scob2XPBgDQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVjZGNXoxU0s4dmxEQzYw
            eUJaT1c2bGgxb0xRWnM5WmdFMkFleklQZVRRCi8xT0R4ck1NLzh1NThwOFRIQ3Nn
            NVlhalVYRytZYlljN291eDRuV1o5OTAKLS0tIFdJeGZDKzNEenZsSitlU1doVnpE
            bkRQenUwZEZZWVlmdjVyVDFZQkNYbjAKCDYmkjo6NPqfoZmrEbXxQUhbjhPfnhCy
            E8lfSvOiYy5PHzH0HwNcLhv46MPW/2b0083mRF5DdPTqJYlGxWOq/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ccnp4g9jp4ap9smug8lvnnag56tz9e3xwkl5hjhzw4uad6xnt5gq2vk63m
    lastmodified: "2026-08-25T18:22:59Z"
    mac: ENC[AES256_GCM,data:avPbkPj45CEBXovESxNQHUStOv6MG7q5fqZR6KdZkWfikTxil19i8K29x/dqIxacIRHR45Air0TMQo5T5GY54+2mDykhzyhoOwhVf9CAJyY6tistTMUugWaCETk0a9p30V4XuG+bXAiTEffWjqWQw6/+TGkSS08JfseOAWa8ADw=,iv:A6OEQ47FhTNhMJBiccyGQeQNLBy7vVkS6hIM8T5vE1I=,tag:mMM+q8tCj3mWR7resdGizg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
