backend:
    databaseUrl: ENC[AES256_GCM,data:UyfDSt8t7p46W+VMNtsXDaWPjxfTVc0t8GA9GN52MFnNRs3qbv7P2xr3cvr22SqodzLnwQhbBjvPZT/rNFz/EY2UMJ5fG8S+th4PklIcR8hgZAwpMWDF2IAiiwqoBCmj,iv:6QdRzrldj1RmM9qqYksesC09EiiYf2YfM4eNBQ9FRvc=,tag:mgEm0jj4d6hXph6aAyUHyw==,type:str]
imagePullSecret:
    username: ENC[AES256_GCM,data:cRVAHhrmqw==,iv:fiVEcbjV4cs7Rml2DgVtkgwNOX3G61SwU9v/wi/Wfic=,tag:Cdo2fS+BCcth3D960Wk3CA==,type:str]
    password: ENC[AES256_GCM,data:b26TISp+QQp+4mXkKJogkSBBh6rtPilHgbu6I80n+xHGqEiiZI3AXA==,iv:2o7CokPPxj8+l9HXFfjNMbsrlqJ9H7Bia93EbX9E4kQ=,tag:/aQc+EImlrAlyXMuNlH6EQ==,type:str]
postgres:
    DB_USER: ENC[AES256_GCM,data:ceIh,iv:s7pw0/EfrebIzQ1cLZIr8dM57bDueezB/woIIz32ZUk=,tag:u54iC3ndGNJ+DttSOyksPA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:sDLMXLj9,iv:qEi60M4+2nQYg9wB352cdxA0uDPb5mzpekcMtCKHfQc=,tag:iuOuOGoPeTJxF8K7CJ5xMA==,type:str]
    DB_NAME: ENC[AES256_GCM,data:E1zIen/3MyA=,iv:5EF2gvtOmY5EZ16PtAmCQCKJUQHho/I2ct36Kp3wGdw=,tag:hZbPNKumj7IgqwpdWiBreg==,type:str]
    PROJECT_ROOT: ENC[AES256_GCM,data:Qw==,iv:40L+R0V30Pk5D+hTRrbGJX5L5IGp/k+6YksABVtZM7A=,tag:z11Wl+fQNL7scob2XPBgDQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVjZGNXoxU0s4dmxEQzYw
            eUJaT1c2bGgxb0xRWnM5WmdFMkFleklQZVRRCi8xT0R4ck1NLzh1NThwOFRIQ3Nn
            NVlhalVYRytZYlljN291eDRuV1o5OTAKLS0tIFdJeGZDKzNEenZsSitlU1doVnpE
            bkRQenUwZEZZWVlmdjVyVDFZQkNYbjAKCDYmkjo6NPqfoZmrEbXxQUhbjhPfnhCy
            E8lfSvOiYy5PHzH0HwNcLhv46MPW/2b0083mRF5DdPTqJYlGxWOq/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ccnp4g9jp4ap9smug8lvnnag56tz9e3xwkl5hjhzw4uad6xnt5gq2vk63m
    lastmodified: "2026-09-16T14:15:37Z"
    mac: ENC[AES256_GCM,data:8sgzXBXlY33IXHQZ1KX6JKefQPQ+HMRRkCeCngwX2ZP1odi3psoKP5pvqB7dUAyF1ivkmtnCf+DyzhmCvbgHNUW2xylphXri4Z3ZbUN5SlPL0mmRFQNZ/nCmF8x65Ff1na0eQklXOSSvdq8diZOlHoddsZKITekI/bPKK3TubPg=,iv:xGJxS7nseeKoIrfrA4k6AGYUjvc9PhJZg1Ms7Z5ARBM=,tag:vcqFkovGmNWVGHNDYWGQZQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
