apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: application
data:
  # property-like keys; each key maps to a simple value
  DB_PORT: "5432"
  DB_HOST: "postgres.database.svc.cluster.local"
  DB_NAME: "cards_db"
