apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-backend-config"
  namespace: {{  .Values.backend.namespace | default "application"  }}
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  DB_PORT: {{ .Values.database.port | quote }}
  DB_HOST: "{{ .Release.Name }}-postgres-service.{{ .Values.database.namespace | default "database" }}.svc.cluster.local"
  DB_NAME: {{ .Values.database.name | default "cards_db" | quote }}
